"""Custom exceptions for expert curriculum generation.

This module defines a hierarchy of exceptions for handling various failure
scenarios during curriculum generation, including API failures, validation
errors, and domain validation issues.
"""

from typing import List, Optional


class CurriculumGenerationError(Exception):
    """Base exception for curriculum generation failures.

    All curriculum-related exceptions inherit from this base class,
    allowing for broad exception handling when needed.
    """

    pass


class APITimeoutError(CurriculumGenerationError):
    """API call exceeded timeout limit.

    Raised when a GPT-5 API call takes longer than the configured timeout
    period. This typically indicates network issues or API overload.

    Attributes:
        timeout: The timeout value in seconds that was exceeded
    """

    def __init__(self, timeout: int):
        self.timeout = timeout
        super().__init__(
            f"API call timed out after {timeout} seconds. "
            f"This may indicate network issues or API overload. "
            f"Try again in a few minutes or check your internet connection."
        )


class APIRateLimitError(CurriculumGenerationError):
    """API rate limit exceeded.

    Raised when the OpenAI API returns a 429 status code, indicating
    too many requests in a short time period.

    Attributes:
        retry_after: Optional number of seconds to wait before retrying
    """

    def __init__(self, retry_after: Optional[int] = None):
        self.retry_after = retry_after
        if retry_after:
            msg = (
                f"Rate limit exceeded. Too many requests in a short time. "
                f"Wait {retry_after} seconds and try again, or check your "
                f"OpenAI usage dashboard."
            )
        else:
            msg = (
                "Rate limit exceeded. Too many requests in a short time. "
                "Wait a minute and try again, or check your OpenAI usage dashboard."
            )
        super().__init__(msg)


class APIServerError(CurriculumGenerationError):
    """API server error (5xx status codes).

    Raised when the OpenAI API returns a server error, indicating
    issues on the API provider's side.

    Attributes:
        status_code: The HTTP status code returned by the API
        message: The error message from the API
    """

    def __init__(self, status_code: int, message: str):
        self.status_code = status_code
        super().__init__(
            f"Server error {status_code}: {message}. This is an issue with the OpenAI API. Try again in a few minutes."
        )


class InvalidCurriculumError(CurriculumGenerationError):
    """Generated curriculum is invalid or malformed.

    Raised when the curriculum generated by GPT-5 fails validation,
    such as missing required fields, invalid values, or structural issues.

    Attributes:
        issues: List of specific validation issues found
    """

    def __init__(self, issues: List[str]):
        self.issues = issues
        issues_str = "\n  - ".join(issues)
        super().__init__(f"Invalid curriculum structure. Issues found:\n  - {issues_str}")


class DomainValidationError(CurriculumGenerationError):
    """Domain is not suitable for autonomous learning.

    Raised when the expert domain is too broad, too narrow, or otherwise
    unsuitable for generating a meaningful learning curriculum.

    Attributes:
        domain: The domain string that failed validation
        reason: Explanation of why the domain is unsuitable
    """

    def __init__(self, domain: str, reason: str):
        self.domain = domain
        self.reason = reason
        super().__init__(
            f"Domain '{domain}' is not suitable for autonomous learning: {reason}\n\n"
            f"Examples of good domains:\n"
            f"  - 'AWS Solutions Architect'\n"
            f"  - 'NVIDIA Omniverse Digital Twins'\n"
            f"  - 'Python FastAPI Development'\n"
            f"  - 'Kubernetes Security'\n\n"
            f"Examples of bad domains:\n"
            f"  - 'Everything about AI' (too broad)\n"
            f"  - 'Python' (too broad, needs focus area)\n"
            f"  - 'My Company's Internal Tool' (no public research available)"
        )


class APIKeyError(CurriculumGenerationError):
    """API key is missing or invalid.

    Raised when the OpenAI API key is not configured or is invalid.

    Attributes:
        key_type: Type of key issue ('missing' or 'invalid')
    """

    def __init__(self, key_type: str = "missing"):
        self.key_type = key_type
        if key_type == "missing":
            msg = "OpenAI API key not found. Set OPENAI_API_KEY in your .env file.\nExample: OPENAI_API_KEY=sk-..."
        else:
            msg = (
                "Invalid OpenAI API key. Check your OPENAI_API_KEY in .env file.\n"
                "Make sure the key is correct and has not expired."
            )
        super().__init__(msg)


class BudgetExceededError(CurriculumGenerationError):
    """Estimated cost exceeds budget limit.

    Raised when the estimated cost of the curriculum exceeds the
    user-specified budget limit.

    Attributes:
        estimated_cost: The estimated cost of the curriculum
        budget_limit: The user-specified budget limit
    """

    def __init__(self, estimated_cost: float, budget_limit: float):
        self.estimated_cost = estimated_cost
        self.budget_limit = budget_limit
        super().__init__(
            f"Estimated cost (${estimated_cost:.2f}) exceeds budget (${budget_limit:.2f}). "
            f"Increase budget with --budget or reduce --topics."
        )


class NetworkError(CurriculumGenerationError):
    """Network connectivity issue.

    Raised when unable to reach the OpenAI API due to network issues.
    """

    def __init__(self):
        super().__init__("Cannot reach OpenAI API. Check your internet connection and try again.")
